import collections

detectors = collections.OrderedDict()

detectors['Pilatus1M 3X'] = {
    'bg_color': 'lightgrey',
    'name': '13PIL3',
    'prefix': 'XRD',
    'monitor_signal_start': '13PIL3:cam1:Acquire',
    'monitor_signal_start_value': 'Acquire',
    'monitor_signal_end': '13PIL3:HDF1:FullFileName_RBV',
    'monitor_signal_end_value': None,
    'monitor_signal_abort': '13PIL3:cam1:DetectorState_RBV',
    'monitor_signal_abort_value': ['Aborted', 'Error'],
    'track_running_tasks': True,
    'frame_type_PV': None,
    'frame_type_values': {0: 'normal', },
    'frame_type_messages': {0: 'Pilatus XRD'},
    'image_type_PV': None,
    'image_type_values': 0,
    'image_type_exposure_time': {0: '13PIL3:cam1:AcquireTime_RBV'},
    'new_file_name': {0: '13PIL3:HDF1:FullFileName_RBV'},
    'comments': '{0}, backup_file: {1}',
    'comments_PVs': ['13PIL3:AcquireSequence.STRA', '13PIL3:cam1:FullFileName_RBV'],
    'comments_values': [None, None],
    'sleep_after_end': 0.0,
    'default_base_name': 'LaB6',
    'default_rel_dir': '',
    'soft_link': '/DAC/',
    'file_path': '13PIL3:HDF1:FilePath',
    'file_name': '13PIL3:HDF1:FileName',
    'file_number': '13PIL3:HDF1:FileNumber',
    'file_type': 'h5',
    'end_clear_pvs': ['13PIL3:AcquireSequence.STRA']
}

detectors['Pilatus1M 3S'] = {
    'bg_color': 'lightgrey',
    'name': '13PIL1MCdTe',
    'prefix': 'XRD',
    'monitor_signal_start': '13PIL1MCdTe:cam1:Acquire',
    'monitor_signal_start_value': 'Acquire',
    'monitor_signal_end': '13PIL1MCdTe:HDF1:FullFileName_RBV',
    'monitor_signal_end_value': None,
    'monitor_signal_abort': '13PIL1MCdTe:cam1:DetectorState_RBV',
    'monitor_signal_abort_value': ['Aborted', 'Error'],
    'track_running_tasks': True,
    'frame_type_PV': None,
    'frame_type_values': {0: 'normal', },
    'frame_type_messages': {0: 'Pilatus XRD'},
    'image_type_PV': None,
    'image_type_values': 0,
    'image_type_exposure_time': {0: '13PIL1MCdTe:cam1:AcquireTime_RBV'},
    'new_file_name': {0: '13PIL1MCdTe:HDF1:FullFileName_RBV'},
    'comments': '{0}, backup_file: {1}',
    'comments_PVs': ['13PIL1MCdTe:AcquireSequence.STRA', '13PIL1MCdTe:cam1:FullFileName_RBV'],
    'comments_values': [None, None],
    'sleep_after_end': 0.0,
    'default_base_name': 'LaB6',
    'default_rel_dir': '',
    'soft_link': '/DAC/',
    'file_path': '13PIL1MCdTe:HDF1:FilePath',
    'file_name': '13PIL1MCdTe:HDF1:FileName',
    'file_number': '13PIL1MCdTe:HDF1:FileNumber',
    'file_type': 'h5',
    'end_clear_pvs': ['13PIL1MCdTe:AcquireSequence.STRA']
}

detectors['Pilatus1M Si'] = {
    'bg_color': 'lightgrey',
    'name': '13PIL1MSi',
    'prefix': 'XRD',
    'monitor_signal_start': '13PIL1MSi:cam1:Acquire',
    'monitor_signal_start_value': 'Acquire',
    'monitor_signal_end': '13PIL1MSi:HDF1:FullFileName_RBV',
    'monitor_signal_end_value': None,
    'monitor_signal_abort': '13PIL1MSi:cam1:DetectorState_RBV',
    'monitor_signal_abort_value': ['Aborted', 'Error'],
    'track_running_tasks': True,
    'frame_type_PV': None,
    'frame_type_values': {0: 'normal', },
    'frame_type_messages': {0: 'Pilatus XRD'},
    'image_type_PV': None,
    'image_type_values': 0,
    'image_type_exposure_time': {0: '13PIL1MSi:cam1:AcquireTime_RBV'},
    'new_file_name': {0: '13PIL1MSi:HDF1:FullFileName_RBV'},
    'comments': '{0}, backup_file: {1}',
    'comments_PVs': ['13PIL1MSi:AcquireSequence.STRA', '13PIL1MSi:cam1:FullFileName_RBV'],
    'comments_values': [None, None],
    'sleep_after_end': 0.0,
    'default_base_name': 'LaB6',
    'default_rel_dir': '',
    'soft_link': '/DAC/',
    'file_path': '13PIL1MSi:HDF1:FilePath',
    'file_name': '13PIL1MSi:HDF1:FileName',
    'file_number': '13PIL1MSi:HDF1:FileNumber',
    'file_type': 'h5',
    'end_clear_pvs': ['13PIL1MSi:AcquireSequence.STRA']
}

detectors['lightfield'] = {
    'name': '13BMCLF1',
    'prefix': 'T',
    'monitor_signal_start': '13BMCLF1:cam1:Acquire',
    'monitor_signal_start_value': 'Acquire',
    'monitor_signal_end': '13BMCLF1:cam1:Acquire',
    'monitor_signal_end_value': 'Done',
    'track_running_tasks': False,
    'frame_type_PV': '13BMCLF1:cam1:ImageMode',
    'frame_type_values': {0: 'normal',
                          2: 'background',
                          },
    'frame_type_messages': {0: 'T',
                            2: 'T BG',
                            },
    'new_file_name': {0: '13BMCLF1:cam1:FullFileName_RBV',
                      2: '13BMCLF1:cam1:LFBackgroundFullFile_RBV'},
    'image_type_PV': '13BMCLF1:cam1:LFExperimentName',
    'image_type_values': {0: 'PIMAX_Ruby',
                          1: 'PIMAX_temperature',
                          2: 'PIMAX_temperature_pulsed',
                          3: 'PIXIS_Raman',
                          4: 'PIXIS_Ruby',
                          5: 'PIXIS_Temperature',
                          },
    'image_type_messages': {0: 'PIMAX Ruby',
                            1: 'PIMAX T',
                            2: 'PIMAX pulsed T',
                            3: 'PIXIS Raman',
                            4: 'PIXIS Ruby',
                            5: 'PIXIS T',
                            },
    'image_type_exposure_time': {0: '13BMCLF1:cam1:LFRepGateWidth',
                                 1: '13BMCLF1:cam1:LFRepGateWidth',
                                 2: '13BMCLF1:cam1:LFRepGateWidth',
                                 3: '13BMCLF1:cam1:AcquireTime',
                                 4: '13BMCLF1:cam1:AcquireTime',
                                 5: '13BMCLF1:cam1:AcquireTime',
                                 6: '13BMCLF1:cam1:AcquireTime',
                                 },

    'comments': 'Filter: {0}, Laser Shutter {1}',
    'comments_PVs': [ ],
    'comments_values': [
        {0: 'Out',
         1: 'In',
         },
        {0: 'CLOSED',
         1: 'Open',
         }
    ],
    'sleep_after_end': 0.5,
    'default_base_name': 't',
    'default_rel_dir': 'T',
    'file_path': '13BMCLF1:cam1:FilePath',
    'file_name': '13BMCLF1:cam1:FileName',
    'file_number': '13BMCLF1:cam1:FileNumber',
    'file_type': 'spe',
    'delay_before_end': 0.2,
}

detectors['ms_visual'] = {
    'name': '13BMCPG2',
    'prefix': 'IM',
    'monitor_signal_start': '13BMCPG2:TIFF1:WriteFile_RBV',
    'monitor_signal_start_value': 'Done',
    'monitor_signal_end': None,
    'monitor_signal_end_value': None,
    'track_running_tasks': False,
    'frame_type_PV': None,
    'frame_type_values': {0: 'normal', },
    'frame_type_messages': {0: 'MS Image', },
    'image_type_PV': None,
    'image_type_values': 0,
    'image_type_exposure_time': {0: '13BMCPG2:cam1:AcquireTime',
                                 },
    'new_file_name': {0: '13BMCPG2:TIFF1:FullFileName_RBV',
                      },
    'comments': '',
    'comments_PVs': [''],
    'comments_values': [],
    'sleep_after_end': 0.0,
    'default_base_name': 'ms_image',
    'default_rel_dir': 'images',
    'file_path': '13BMCPG2:TIFF1:FilePath',
    'file_name': '13BMCPG2:TIFF1:FileName',
    'file_number': '13BMCPG2:TIFF1:FileNumber',
    'file_type': 'tif',
}

detectors['bv_visual'] = {
    'name': '13BV1',
    'prefix': 'IM',
    'monitor_signal_start': '13BV1:TIFF1:WriteFile_RBV',
    'monitor_signal_start_value': 'Done',
    'monitor_signal_end': None,
    'monitor_signal_end_value': None,
    'track_running_tasks': False,
    'frame_type_PV': None,
    'frame_type_values': {0: 'normal', },
    'frame_type_messages': {0: 'BV Image', },
    'image_type_PV': None,
    'image_type_values': 0,
    'image_type_exposure_time': {0: '13BV1:cam1:AcquireTime',
                                 },
    'new_file_name': {0: '13BV1:TIFF1:FullFileName_RBV',
                      },
    'comments': '',
    'comments_PVs': [''],
    'comments_values': [],
    'sleep_after_end': 0.0,
    'default_base_name': 'bv_image',
    'default_rel_dir': 'images',
    'file_path': '13BV1:TIFF1:FilePath',
    'file_name': '13BV1:TIFF1:FileName',
    'file_number': '13BV1:TIFF1:FileNumber',
    'file_type': 'tif',
}

